### ISSUE TITLE
cloudar.be link is broken

### ISSUE THREAD

**Issue by za** [WeAreCloudar/s3-account-search#10]
Hi https://www.cloudar.be/awsblog/finding-the-accountid-of-any-public-s3-bucket/ it's returning 404 :/
I'd like to understand more on the concept how to get account id from S3 bucket.

Thanks

**Comment by benbridts** [comment]
This link should work, although I believe AWS have plugged this hole now

https://cloudar.be/awsblog/finding-the-account-id-of-any-public-s3-bucket/
